config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
  
  root 'landing_page#best'

  resources :users

  get 'questions' => 'questions#index'

  get 'best' => 'landing_page#best'
  get 'perfect' => 'landing_page#perfect'
  get 'right' => 'landing_page#right'
  get 'sign_up' => 'landing_page#sign_up'
  get 'success' => 'landing_page#success'

  resources :recommendations, only: [:create]

end

app/models/question.rb
class Question
  include ActiveModel::Model

  attr_accessor :text, :answers

  def self.all
    [Question.new(
      text: 'How big is your grilling space?',
      answers: [ { text: 'Big' }, { text: 'Small' }]
    ),
    Question.new(
      text: 'How many people do you typically cook for?',
      answers: [{ text: 'Few' }, { text: 'Lots' }]
    ),
    Question.new(
      text: 'What style of grill do you prefer?',
      answers: [ { text: 'New' }, { text: 'Traditional' }]
    )]
  end
end

app/models/recommendation.rb
class Recommendation
  include ActiveModel::Model

  attr_accessor :name, :price, :img, :link
  def self.find_by_answers answers
    all[answers]
  end

  def self.all
    {
      ['Small', 'Few', 'Traditional'] => Recommendation.new(name: 'American Gourmet charcoal grill', price: '$129.99', link: 'http://www.lowes.com/pd_551860-451-12301567_0__?Ntt=american+gourmet+grill&UserSearch=american+gourmet+grill&productId=50202851&rpp=32', img: 'american-gourmet.jpg'),
      ['Small', 'Lots', 'Traditional'] => Recommendation.new(name: 'Char-Broil 2-burner gas grill', price: '$189.00', link: 'http://www.charbroil.com/grills/gas-grills/charbroil-traditional-gas-grills/gas-grill-value-series-463622514.html', img: 'charbroil-2-burner.jpg'),
      ['Small', 'Few', 'New'] => Recommendation.new(name: 'Patio Bistro 240 TRU-Infrared electric grill', price: '$189.00', link: 'http://www.lowes.com/pd_551866-451-12601688_0__?productId=50201323&Ntt=patio+bistro+240+electric&pl=1&currentURL=%3FNtt%3Dpatio%2Bbistro%2B240%2Belectric&facetInfo=', img: 'patio-bistro-240-electric.jpg'),
      ['Small', 'Lots', 'New'] => Recommendation.new(name: 'Commercial TRU-Infrared 2-burner gas grill', price: '$269.00', link: 'http://www.lowes.com/pd_404328-82210-463241014_0__?Ntt=commercial+2+burner+gas+grill&UserSearch=commercial+2+burner+gas+grill&productId=50029234&rpp=32', img: 'commercial-2-burner.jpg'),
      ['Big', 'Few', 'Traditional'] => Recommendation.new(name: 'Char-Broil Classic 3-burner gas grill', price: '$199.99', link: 'http://www.charbroil.com/grills/gas-grills/charbroil-traditional-gas-grills/char-broil-classic-c-33g3-model-463722313.html', img: 'classic-3-burner.jpg'),
      ['Big', 'Lots', 'Traditional'] => Recommendation.new(name: 'Char-Broil Classic 6-burner gas grill', price: '$389.00', link: 'http://www.charbroil.com/gas-grill-k6b-650-lidded-sideburners-463230514.html', img: 'classic-6-burner.png'),
      ['Big', 'Few', 'New'] => Recommendation.new(name: 'Performance TRU-Infrared 3-burner gas grill', price: '$349.00', link: 'http://www.charbroil.com/char-broil-performance-3-burner-tru-ir-gas-grill-463270914.html', img: 'performance-3-burner.png'),
      ['Big', 'Lots', 'New'] => Recommendation.new(name: 'Performance TRU-Infrared 4-burner gas grill', price: '$549.00', link: 'http://www.charbroil.com/char-broil-performance-tru-infrared-4-burner-t-4-463271314.html', img: 'performance-4-burner.jpg')
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
  attr_accessor :email, :experiment_group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def create
    @recommendation = Recommendation.find_by_answers(params[:answers])
    render json: {
      name: @recommendation.name,
      price: @recommendation.price,
      link: @recommendation.link,
      img: ActionController::Base.helpers.asset_path(@recommendation.img) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new user_params
    @user.save
    render 'landing_page/success'
  end

  def user_params
    params.require(:user).permit :email
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/landing_page/best.haml
#landing-page
  #hero
    = image_tag "grilling.jpg"
  .content-container
    %h1.headline
      Find The Best Grill For You
    %p.body-copy
      Are you looking for a backyard powerhouse? A trusty tailgate companion? We can help you filter through the noise.
    = link_to 'Get Started', '/sign_up', :class => "main-call-to-action"

app/views/landing_page/perfect.haml
#landing-page
  #hero
    = image_tag "grilling.jpg"
  .content-container
    %h1.headline
      Find Your Perfect Grill
    %p.body-copy
      Are you looking for a backyard powerhouse? A trusty tailgate companion? We can help you filter through the noise.
    = link_to 'Get Started', '/sign_up', :class => "main-call-to-action"

app/views/landing_page/right.haml
#landing-page
  #hero
    = image_tag "grilling.jpg"
  .content-container
    %h1.headline
      Find The Right Grill For You
    %p.body-copy
      Are you looking for a backyard powerhouse? A trusty tailgate companion? We can help you filter through the noise.
    = link_to 'Get Started', '/sign_up', :class => "main-call-to-action"

app/views/landing_page/sign_up.haml
#sign-up
  #hero
    = image_tag "grilling.jpg"
  .content-container
    %h1.headline
      Coming soon
    %p.body-copy
      We're working on a recommendation tool that focuses on your lifestyle and what you value when looking to invest in a new grill. Simple questions, one great answer.
    %p.body-copy
      Enter your e-mail below, and we'll let you know once it's ready for primetime. 
    #email.email-submit
      = form_tag '/users' do
        = email_field :user, :email, :placeholder => "e-mail address"
        = submit_tag "submit email"

app/views/landing_page/success.haml
#success
  #hero
    = image_tag "grilling.jpg"
  .content-container
    %h1.headline
      Thanks!
    %p.body-copy
      We'll be in touch soon.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Find Your Grill</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">
</head>
<body>

<%= yield %>

</body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55676723-1', 'auto');
  ga('send', 'pageview');

  $(function() {
    $.ajaxSetup({
      headers: { 'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content') }
    });
  });
</script>
</html>

app/views/questions/index.html.haml
#quiz
  .welcome{'data-bind' => 'ifnot: started'}
    %h2 FIND THE BEST GRILL FOR YOU
    %p Are you looking for a backyard powerhouse? A trusty tailgate companion? We can help you filter through the noise.
    %button{'data-bind' => 'click: startQuiz'} Start
  .questions{'data-bind' => 'if: started'}
    .question{'data-bind' => 'with: question'}
      %p{'data-bind' => 'text: text'}
        .answers{'data-bind' => 'foreach: answers'}
          %button{'data-bind' => 'text: text, click: $root.answerQuestion'}

  .recommendation{'data-bind' => 'with: recommendation'}
    #image
      %img{'data-bind' => 'attr: { src: img }' }
    #description
      %p{'data-bind' => 'text: name' }
      %p{'data-bind' => 'text: price' }
    %a{'data-bind' => 'attr: { href: link}, text: "Buy me"' }


:javascript
  $(function() {
    ko.applyBindings(new Quiz(#{@questions.to_json.html_safe}, '#{recommendations_path}'), $('#quiz').get(0));
  });